export const CONFIG =
{
  USER_PROFILE:
  {
    MINIMUM_AGE: 13,
    MAXIMUM_AGE: 70,
    DEFAULT_AGE: 18,
    DEFAULT_RETIREMENT_AGE: 65,
    RADIUS_IN_MILES: 25,
    RETIREMENT_AGE_MINIMUM: 40,
    RETIREMENT_AGE_MAXIMUM: 80,
  },
  EDUCATION_COST:
  {
    YEARS_TO_COMPLETE_MINIMUM: 1,
    YEARS_TO_COMPLETE_DEFAULT: 4,
    YEARS_TO_COMPLETE_MAXIMUM: 8
  },
  EDUCATION_FINANCING:
  {
    DEFAULT_PAY_OFF_FEDERAL_LOAN_IN_YEARS: 10,
    DEFAULT_PAY_OFF_PRIVATE_LOAN_IN_YEARS: 8
  }
};
